matrix:
  include:
    - os: osx
      env: ACTION=carthage
    - os: osx
      env: ACTION=CocoaPods
    - os: osx
      env: ACTION=SwiftPM
    - os: osx
      env: ACTION=tvOS
    - os: osx
      env: ACTION=iOS
    - os: osx
      env: ACTION=macOS
    - os: linux
      language: generic
      dist: trusty
      sudo: required
      services:
        - docker
      script:
        - make test-docker

language: objective-c
osx_image: xcode10.1

script:
  - make install-$ACTION && make test-$ACTION
